{{- if and .Values.backend.env.database.url (not .Values.backend.env.database.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "clustervision.fullname" . }}-database
  namespace: {{ include "clustervision.namespace" . }}
  labels:
    {{- include "clustervision.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-url: {{ .Values.backend.env.database.url | quote }}
{{- end }}
