{{- if and .Values.backend.env.ldap.enabled .Values.backend.env.ldap.bindPassword (not .Values.backend.env.ldap.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "clustervision.fullname" . }}-ldap
  namespace: {{ include "clustervision.namespace" . }}
  labels:
    {{- include "clustervision.labels" . | nindent 4 }}
type: Opaque
stringData:
  bind-password: {{ .Values.backend.env.ldap.bindPassword | quote }}
{{- end }}
