apiVersion: v1
kind: Service
metadata:
  name: {{ include "clustervision.fullname" . }}-backend
  namespace: {{ include "clustervision.namespace" . }}
  labels:
    {{- include "clustervision.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "clustervision.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: backend
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: 8000
      name: http
