{{- if and .Values.vault.enabled .Values.vault.token (not .Values.vault.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "clustervision.fullname" . }}-vault
  namespace: {{ include "clustervision.namespace" . }}
  labels:
    {{- include "clustervision.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ .Values.vault.token | quote }}
{{- end }}
