name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"

categories:
  - title: "🚀 Nouveautés"
    labels:
      - feature
      - enhancement
  - title: "🐛 Corrections"
    labels:
      - fix
      - bugfix
      - bug
  - title: "🔧 Maintenance"
    labels:
      - chore
      - dependencies
      - dependabot
  - title: "📖 Documentation"
    labels:
      - documentation
      - docs
  - title: "🏗️ Infrastructure"
    labels:
      - helm
      - ci
      - docker

version-resolver:
  major:
    labels:
      - breaking
  minor:
    labels:
      - feature
      - enhancement
  patch:
    labels:
      - fix
      - bugfix
      - bug
      - chore
      - dependencies
      - helm
      - ci
      - docker
      - docs
  default: patch

template: |
  ## Changements

  $CHANGES

  **Image Docker** : `ghcr.io/j4rj4r/clustervision-backend:$RESOLVED_VERSION`

  **Helm chart** :
  ```bash
  helm upgrade --install clustervision oci://ghcr.io/j4rj4r/charts/clustervision \
    --version $RESOLVED_VERSION \
    --namespace clustervision
  ```
