{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "clustervision.serviceAccountName" . }}
  namespace: {{ include "clustervision.namespace" . }}
  labels:
    {{- include "clustervision.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
{{- end }}
